version: "3"

services:
  mihoyo-bbs:
    image: womsxd/mihoyo-bbs
    restart: always
    environment:
      - CRON_SIGNIN=30 9 * * *
      - MULTI=TRUE
    volumes:
      - ./config:/var/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
