#这里控制整个config文件是否启用
enable: true
#config的版本
version: 15
# todo功能
push: ""
account:
  #登入账号只需要修改cookie就行了
  cookie: ""
  stuid: ""
  stoken: ""
  mid: ""
device:
  name: "Xiaomi MI 6"
  model: "Mi 6"
  # 此处留空则脚本随机生成
  id: ""
  # 手动获取
  fp: ""
mihoyobbs:
  #控制bbs功能是否启用
  enable: false
  #社区签到
  checkin: true
  #签到的社区列表 详情可以看config文件夹下面的readme
  checkin_list:
    - 2
    - 6
  #看帖
  read: true
  #点赞帖子
  like: true
  #取消点赞
  cancel_like: true
  #分享帖子
  share: true
# 游戏签到
games:
  #国服控制区域
  cn:
    #控制是否启用国内签到
    enable: false
    #配置签到用的ua 脚本会在后面自动加上miHoYoBBS/版本号 ,请复制的时候不要带miHoYoBBS/版本
    useragent: "Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
    #重试次数
    retries: 3
    #原神
    genshin:
      #控制是否启用签到，下面一致
      checkin: true
      #这里是不签到的账号，填入文本型数据 示例["114514","1919810"](也许你这边是和checkin_list那块一样)，下面一致
      black_list: []
    #崩坏2
    honkai2:
      checkin: false
      black_list: []
    #崩坏3
    honkai3rd:
      checkin: false
      black_list: []
    #未定事件簿
    tears_of_themis:
      checkin: false
      black_list: []
    # 崩坏: 星穹铁道
    honkai_sr:
      checkin: true
      black_list: []
    #绝区零
    zzz:
      checkin: true
      black_list: []
  #国际服控制区域
  os:
    enable: true
    # 国际服专用Cookie填写
    cookie: "
mi18nLang=zh-cn; _HYVUUID=c495d2eb-2d87-446f-a73c-361f0e533a2d; HYV_LOGIN_PLATFORM_OPTIONAL_AGREEMENT={%22content%22:[]}; HYV_LOGIN_PLATFORM_TRACKING_MAP={%22sourceValue%22:%22422%22}; DEVICEFP_SEED_ID=ec9367e1ebe4ff65; DEVICEFP_SEED_TIME=1756119021947; DEVICEFP=38d7f5d370a2f; cookie_token_v2=v2_CAQSDGM5b3FhcTNzM2d1OBokYzQ5NWQyZWItMmQ4Ny00NDZmLWE3M2MtMzYxZjBlNTMzYTJkIO-EscUGKND4mpEDMLTMknhCC2Jic19vdmVyc2Vh.b0KsaAAAAAAB.MEYCIQC4z5j7Z8iGLBgV1uur9qx9jEDCTh0uW0cwXK-9yCOhqgIhANGS-J2r4wLQ5aYM1iQ_H2FpkjaPKOSxpJr3XeYIYNw2; account_mid_v2=1r1w0166jf_hy; account_id_v2=251962932; ltoken_v2=v2_CAISDGM5b3FhcTNzM2d1OBokYzQ5NWQyZWItMmQ4Ny00NDZmLWE3M2MtMzYxZjBlNTMzYTJkIO-EscUGKKq075QGMLTMknhCC2Jic19vdmVyc2Vh.b0KsaAAAAAAB.MEUCIHV23lixhTgm16sFr6LOrrSqc3-CyYe_ESH74NeFgmmJAiEApn3Mk1H-QU-axCRTMRmLRUPWOHywQC7oakbC63yH5w4; ltmid_v2=1r1w0166jf_hy; ltuid_v2=251962932; HYV_LOGIN_PLATFORM_LIFECYCLE_ID={%22value%22:%223240a282-fed2-441f-85b1-9f80b5a05c83%22}; HYV_LOGIN_PLATFORM_LOAD_TIMEOUT={}"
    # 国际服语言
    lang: "zh-cn"
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: [ ]
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: true
      black_list: []
    zzz:
      checkin: true
      black_list: []
#云游戏专区
cloud_games:
  # 控制整个云游戏的签到
  cn:
    enable: false
    #云原神
    genshin:
      #开启签到
      enable: false
      #这里填入抓包获得的token，支持多个
      token: ""
    #云绝区零
    zzz:
      enable: false
      token: ""
  os:
    lang: "zh-cn"
    enable: false
    genshin:
      enable: false
      token: ""
competition:
  enable: false
  # 功能已经移除
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
# 网页活动
web_activity:
  enable: false
  # 需要激活的活动名称["xx1","xx2"]
  activities: []
