#这里控制整个config文件是否启用
enable: true
#config的版本
version: 15
# todo功能
push: ""
account:
  #登入账号只需要修改cookie就行了
  cookie: "_MHYUUID=4404a700-9605-421d-908c-a6046735db85; DEVICEFP_SEED_ID=be8d5e0ba708ae39; DEVICEFP_SEED_TIME=1784650372542; DEVICEFP=38d81aab8e2e9; MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=80796ca785; cookie_token_v2=v2_Q6naUADTOc3jpot248nVyNPSrEaZolDvr6HkPOnSTHbYp-7lwJXvFZV2R-5ldLxS3e0VK23kwCdei43rJsa9DxicSLfvlRgncw88_hS3pcVtx0_tMpS5f4wLPkvfK-faLDRhrympH_qUE3FJ9g==.CAE=; account_mid_v2=0oapz85j2y_mhy; account_id_v2=20344972; ltoken_v2=v2_6-kZ_xMTJLvnE86tFofClASl1w-lxFusSnu9DSQ7A7vAmYtPrkhCrbf8KHvhM4_qKiZKpcYjhz-aIoLD4Kgr_o59t_mR12ZhhI_kgvBgkK2EOp00e8UBAJceH1KCjyCT0bbW3U5iaav_hM1aHQ==.CAE=; ltmid_v2=0oapz85j2y_mhy; ltuid_v2=20344972; cookie_token=fFnsiYlWo2IqAmuVJy3yZ8hWDqbOgrw6dPmWNPRc; account_id=20344972; ltoken=66XTID2jwy52S3pah0ycU7fO52ZtFCymFYIZg7zm; ltuid=20344972"
  stuid: "20344972"
  stoken: "v2_AocKKpB7HcV2YwG96m9Q-pO86uJHv6uGbdXi6Yq4A0cN_fK94lJSsx5LyzQkOciRNuT7ctCFTwyXyugiajTyIrsSCGqc4hv949uQF-0RFvMQIdyx00L6vZ0=.CAE=;device_id=;device_fp=38d81aaafef55"
  mid: "0oapz85j2y_mhy"
device:
  name: "Xiaomi MI 6"
  model: "Mi 6"
  # 此处留空则脚本随机生成
  id: ""
  # 手动获取
  fp: ""
mihoyobbs:
  #控制bbs功能是否启用
  enable: false
  #社区签到
  checkin: true
  #签到的社区列表 详情可以看config文件夹下面的readme
  checkin_list:
    - 2
    - 6
  #看帖
  read: true
  #点赞帖子
  like: true
  #取消点赞
  cancel_like: true
  #分享帖子
  share: true
# 游戏签到
games:
  #国服控制区域
  cn:
    #控制是否启用国内签到
    enable: true
    #配置签到用的ua 脚本会在后面自动加上miHoYoBBS/版本号 ,请复制的时候不要带miHoYoBBS/版本
    useragent: "Mozilla/5.0 (Linux; Android 12; Unspecified Device) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36"
    #重试次数
    retries: 3
    #原神
    genshin:
      #控制是否启用签到，下面一致
      checkin: true
      #这里是不签到的账号，填入文本型数据 示例["114514","1919810"](也许你这边是和checkin_list那块一样)，下面一致
      black_list: []
    #崩坏2
    honkai2:
      checkin: false
      black_list: []
    #崩坏3
    honkai3rd:
      checkin: true
      black_list: ["504664286","271904942"]
    #未定事件簿
    tears_of_themis:
      checkin: false
      black_list: []
    # 崩坏: 星穹铁道
    honkai_sr:
      checkin: true
      black_list: []
    #绝区零
    zzz:
      checkin: true
      black_list: []
  #国际服控制区域
  os:
    enable: false
    # 国际服专用Cookie填写
    cookie: ""
    # 国际服语言
    lang: "zh-cn"
    genshin:
      checkin: false
      black_list: []
    honkai3rd:
      checkin: false
      black_list: [ ]
    tears_of_themis:
      checkin: false
      black_list: []
    honkai_sr:
      checkin: false
      black_list: []
    zzz:
      checkin: false
      black_list: []
#云游戏专区
cloud_games:
  # 控制整个云游戏的签到
  cn:
    enable: false
    #云原神
    genshin:
      #开启签到
      enable: true
      #这里填入抓包获得的token，支持多个
      token: "ai=4;ci=1;oi=20344972;ct=v2_ed6b6916b45fb2c656ffba5d3bebfc5ce64ed253;si=e1dc7751f6b374aa70a3a26f27574a3b8d3827e1edecb153f2e40d2338450c6e;bi=hk4e_cn"
    #云绝区零
    zzz:
      enable: true
      token: "ai=12;ci=1;oi=20344972;ct=v2_07211fe87324af5baec4ca6b32218b6a1770f7b7;si=3b127bc351513b034417e5632dc751995c579f7c86994e28d1cb00e9ab8f988e;bi=nap_cn"
  os:
    lang: "zh-cn"
    enable: false
    genshin:
      enable: false
      token: ""
competition:
  enable: false
  # 功能已经移除
  genius_invokation:
    enable: false
    account: []
    checkin: false
    weekly: false
# 网页活动
web_activity:
  enable: false
  # 需要激活的活动名称["xx1","xx2"]
  activities: []
